/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PlaylistsImport } from './routes/playlists'
import { Route as IndexImport } from './routes/index'
import { Route as PlaylistIdImport } from './routes/playlist.$id'

// Create/Update Routes

const PlaylistsRoute = PlaylistsImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistIdRoute = PlaylistIdImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsImport
      parentRoute: typeof rootRoute
    }
    '/playlist/$id': {
      id: '/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlaylistIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playlists': typeof PlaylistsRoute
  '/playlist/$id': typeof PlaylistIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playlists': typeof PlaylistsRoute
  '/playlist/$id': typeof PlaylistIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/playlists': typeof PlaylistsRoute
  '/playlist/$id': typeof PlaylistIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/playlists' | '/playlist/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/playlists' | '/playlist/$id'
  id: '__root__' | '/' | '/playlists' | '/playlist/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaylistsRoute: typeof PlaylistsRoute
  PlaylistIdRoute: typeof PlaylistIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaylistsRoute: PlaylistsRoute,
  PlaylistIdRoute: PlaylistIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/playlists",
        "/playlist/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/playlists": {
      "filePath": "playlists.tsx"
    },
    "/playlist/$id": {
      "filePath": "playlist.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
