// This file is auto-generated by @hey-api/openapi-ts

export const DetailedPlaylistSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 100
        },
        tracks: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Track'
            }
        }
    },
    required: ['id', 'name', 'tracks']
} as const;

export const PatchedPlaylistSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 100
        },
        tracks: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const PatchedTrackSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            maxLength: 10
        },
        title: {
            type: 'string',
            maxLength: 200
        },
        length: {
            type: 'integer',
            maximum: 2147483647,
            minimum: -2147483648
        },
        bpm: {
            type: 'integer',
            maximum: 2147483647,
            minimum: -2147483648
        },
        genres: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        moods: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        main_artists: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        featured_artists: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        audio: {
            type: 'string',
            readOnly: true
        },
        cover_art: {
            type: 'string',
            readOnly: true
        },
        waveform: {
            type: 'string',
            readOnly: true
        },
        spotify: {
            type: 'string',
            readOnly: true
        }
    }
} as const;

export const PlaylistSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 100
        },
        tracks: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['id', 'name', 'tracks']
} as const;

export const TrackSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            maxLength: 10
        },
        title: {
            type: 'string',
            maxLength: 200
        },
        length: {
            type: 'integer',
            maximum: 2147483647,
            minimum: -2147483648
        },
        bpm: {
            type: 'integer',
            maximum: 2147483647,
            minimum: -2147483648
        },
        genres: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        moods: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        main_artists: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        featured_artists: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        audio: {
            type: 'string',
            readOnly: true
        },
        cover_art: {
            type: 'string',
            readOnly: true
        },
        waveform: {
            type: 'string',
            readOnly: true
        },
        spotify: {
            type: 'string',
            readOnly: true
        }
    },
    required: ['audio', 'cover_art', 'featured_artists', 'genres', 'id', 'main_artists', 'moods', 'spotify', 'title', 'waveform']
} as const;